### ISSUE TITLE
Shell detection failure inside docker image on ARM Macbook

### ISSUE THREAD

**Issue by ltalirz** [sarugaku/shellingham#55]
We have a docker container, for which we're running into a shell detection failure:
```
Traceback (most recent call last):
  File "/opt/conda/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 777, in main
    _bashcomplete(self, prog_name, complete_var)
  File "/opt/conda/lib/python3.7/site-packages/click_completion/patch.py", line 122, in _shellcomplete
    echo(get_code(prog_name=prog_name, env_name=complete_var))
  File "/opt/conda/lib/python3.7/site-packages/click_completion/core.py", line 299, in get_code
    shell = get_auto_shell()
  File "/opt/conda/lib/python3.7/site-packages/click_completion/lib.py", line 125, in get_auto_shell
    return shellingham.detect_shell()[0]
  File "/opt/conda/lib/python3.7/site-packages/shellingham/__init__.py", line 24, in detect_shell
    raise ShellDetectionFailure()
shellingham._core.ShellDetectionFailure
```
For some reason, this only happens when running the docker container on M1 Macbooks (on Intel Macbooks, the error in the container does not occur). Observations:

 * Shellingham version in container is 1.4.0
 * Shellingham 1.4.0 in a local conda environment on my machine detects the shell just fine (tested with both python 3.7 and 3.9)
 * Both inside container and on my machine, the detected `os.name` is `posix`

For some reason, the shell detection for posix returns `None`
https://github.com/sarugaku/shellingham/blob/325c643e89877eb325adf44bc62547251e87acef/src/shellingham/posix/__init__.py#L82-L90

## Steps to reproduce:
1. Own a Macbook M1 (sorry!)
2. 
```
docker run -d -it --name aiida-core aiidateam/aiida-core:1.6.5
docker exec -it --user aiida aiida-core bash
```

**Comment by ltalirz** [comment]
If you have an idea what could be the reason, I'd be happy to look deeper inside `get_shell` to see where the problem lies

**Comment by uranusjr** [comment]
I don't have an ARM machine to test this out, so you'll probably need to debug this mostly on your own. Note that macOS and Linux are likely using different implementations (macOS uses the `ps` implementation, and Linux the `/proc`-based one) and will need to be debugged separately (although I do kind of suspect the root cause is the same).

I'd probably start with doing something like

```python
>>> import shellingham.posix.proc
>>> print(shellingham.posix.proc.get_process_mapping())
```

and see if there's anything like a shell in there. If not, I'd manually break the loop apart and see where the parsing code went wrong. The fact that this does not happen if you use a native container seems to also indicate that this is something related to the cross-arch translation; maybe a process of Python built against Intel can't map its pid correctly to native ARM? No idea to be honest.

**Comment by uranusjr** [comment]
> I should note that there is also no shell in the output of `ps` (is this expected)?

Maybe. I don't really understand this behaviour either, probably due to some kind of magic in Docker or the Linux kernel. But in any way, if the OS is not reporting the existence of a shell, there's really nothing we can do… The application using shellingham is supposed to [provide a reasonable default](https://github.com/sarugaku/shellingham#notes-for-application-developers) because this kind of oddities do happen, and shell detection can only do so much. This can probably be better explained by some Docker or OCI or Linux on ARM expert, and I am really none of those.

**Comment by brandonros** [comment]
```shell
git clone git@github.com:HenryFBP/trading-bot.git
cd trading-bot/
DOCKER_DEFAULT_PLATFORM=linux/amd64 docker run -it -v $(pwd):/mnt python:3.7-slim bash
# from inside the running Docker shell
cd /mnt
pip install pipenv
pipenv --python /usr/local/bin/python install
pipenv shell
```

I get this even trying to "abstract" away the arm64 and stick to good ol x86_64 (amd64) through emulation

```
# pipenv shell
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 429, in shell
    pypi_mirror=state.pypi_mirror,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2442, in do_shell
    shell = choose_shell(project)
  File "/usr/local/lib/python3.7/site-packages/pipenv/shells.py", line 239, in choose_shell
    type_, command = detect_info(project)
  File "/usr/local/lib/python3.7/site-packages/pipenv/shells.py", line 29, in detect_info
    raise ShellDetectionFailure
pipenv.vendor.shellingham._core.ShellDetectionFailure
```

**Comment by brandonros** [comment]
```
PIPENV_SHELL='/bin/bash' pipenv shell
Launching subshell in virtual environment...
 . /root/.local/share/virtualenvs/mnt-MaCywDhH/bin/activate
root@65c4a982e2d5:/mnt#  . /root/.local/share/virtualenvs/mnt-MaCywDhH/bin/activate
(mnt) root@65c4a982e2d5:/mnt# 
```

That fixes it for some reason?

**Comment by uranusjr** [comment]
Shellingham is never called if you set `PIPENV_SHELL`, since the variable forces `pipenv shell` to use that instead of doing any detection. So yeah, you could use that to work around whatever the problem is here.

**Comment by uranusjr** [comment]
Alright I finally have a chance to look into this. So for this specific environment combination (an Intel image running in Docker on ARM Mac), the parent process is (interestingly) hooked to a different TTY from the Python process itself. I suspect this is due to some simulation implementation detail that leaked into the container. So this is “easily” amendable by removing the TTY check, but I’m hesitant to just do that since it makes the proc implementation quite a bit slower.

An alternative approach would be to do some refactoring and make process look up lazier, so we only access process IDs that are related to the current process. I’m not particularly motivated to do this myself (especially considering that setting `PIPENV_SHELL` is a pretty adequate workaround), but anyone would be much welcomed to contribute to this.
